language: c
compiler:
  - gcc
  - clang
env:
  -
  - MY_SANITIZE=address
  - MY_SANITIZE=undefined
  - MY_SANITIZE=integer
  - MY_VALGRIND=1
  - MY_COVERAGE=1
matrix:
  exclude:
    # Pairs because of some comilers does not support some features at all
    - compiler: gcc
      env: MY_SANITIZE=address
    - compiler: gcc
      env: MY_SANITIZE=undefined
    - compiler: gcc
      env: MY_SANITIZE=integer
    - compiler: clang
      env: MY_VALGRIND=1
    - compiler: clang
      env: MY_COVERAGE=1
before_install:
  - ./.travis.before_install.sh
install:
  - ./autogen.sh
  - ./configure
  - make
script:
  - make cppcheck
  - make test
after_success:
  - if [ "x$MY_COVERAGE" = "x1" ]; then cpp-coveralls --build-root src --exclude src/.libs --gcov-options '\-lp'; fi
